//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [Required(ErrorMessage = "* Required")]
        public int ProductID { get; set; }
        [Required(ErrorMessage ="* Required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "* Required")]
        public string ProductNumber { get; set; }
        [Required(ErrorMessage = "* Required")]
        public string Color { get; set; }
        [Required(ErrorMessage = "* Required")]
        [Range(typeof(decimal), minimum: "0.0", maximum: "79228162514264337593543950335", ErrorMessage = "* Value must be positive")]
        public decimal StandardCost { get; set; }
        [Required(ErrorMessage = "* Required")]
        [Range(typeof(decimal), minimum: "0.0", maximum: "79228162514264337593543950335", ErrorMessage = "* Value must be positive")]
        public decimal ListPrice { get; set; }
        [Required(ErrorMessage = "* Required")]
        public string Size { get; set; }
        [Required(ErrorMessage = "* Required")]
        [Range(typeof(decimal), minimum:"0.0", maximum: "79228162514264337593543950335", ErrorMessage ="* Value must be positive")]
        public Nullable<decimal> Weight { get; set; }
        [Required]
        [Range(minimum: 5, maximum: 7, ErrorMessage = "* Required")]
        public Nullable<int> ProductCategoryID { get; set; }
        [Required]
        public Nullable<int> ProductModelID { get; set; }
        [Required(ErrorMessage = "* Required")]
        public System.DateTime SellStartDate { get; set; }
        public Nullable<System.DateTime> SellEndDate { get; set; }
        public Nullable<System.DateTime> DiscontinuedDate { get; set; }
        public byte[] ThumbNailPhoto { get; set; }
        public string ThumbnailPhotoFileName { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
